export const NativeEmoji = {
  fire: "🔥",
  sparkles: "✨",
  crown: "👑",
  eyes: "👀",
  wave: "👋",

  // Faces
  neutralFace: "😐",
  pensive: "😔",
  disappointed: "😖",
  angry: "😠",
  slighted: "😕",
  worried: "😣",
  neutral: "😐",
  sighing: "😪",
  dottedLineFace: "🫥",

  // Hearts
  mendingHeart: "❤️‍🩹",
  brokenHeart: "💔",
  revolvingHearts: "💞",
  sparklingHeart: "💖",
  heart: "❤️",
  pinkheart: "🩷",
  orangeheart: "🧡",
  yellowheart: "💛",
  greenheart: "💚",
  lightblueheart: "🩵",
  blueheart: "💙",
  purpleheart: "💜",
  blackheart: "🖤",
  whiteheart: "🤍",
  brownheart: "🤎",
} as const satisfies Record<string, string>;
